wso2/carbon-kernel

core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/AbstractUserStoreManager.java
This contains Fixes for IDENTITY-3052 and APPM-333
=> Fixes for IDENTITY-3052 and APPM-333

core/org.wso2.carbon.registry.core/src/main/java/org/wso2/carbon/registry/core/utils/RegistryUtils.java
Issue fixed : When MySQL uses as database, it sends lot of SELECT USER() queries inbetween other queries.
=> Fixed Public JIRA : REGISTRY-2429

core/org.wso2.carbon.core/src/main/java/org/wso2/carbon/core/multitenancy/transports/TenantTransportSender.java
Fix for SERVICE_PREFIX property is not set for tenant in MessageContext
=> Fixing CARBON-15184

core/org.wso2.carbon.registry.api/pom.xml, core/org.wso2.carbon.registry.core/pom.xml, core/org.wso2.carbon.user.core/src/test/java/org/wso2/carbon/user/core/claim/AdvancedClaimManagerTest.java, distribution/integration/tests-new/pom.xml, distribution/integration/tests/pom.xml, distribution/kernel/carbon-home/bin/wso2server.sh, parent/pom.xml
=> Changes for Java 8

core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/AbstractUserStoreManager.java, core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/util/UserCoreUtil.java
Reverts wso2/carbon4-kernel#184
=> Reverting "Fixing IDENTITY-3130" since carbon-4.4.0 Beta is releasing today. Will merge again tomorrow :)

core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/authorization/AuthorizationKey.java
Merging fix done for IDENTITY-2722\CARBON-14896
This is also same as PR : https://github.com/wso2-dev/carbon4-kernel/pull/100
=> Resending fix for IDENTITY-2722

distribution/kernel/carbon-home/repository/conf/etc/carboncontext-osgi-services.properties
Signed-off-by: Jayanga Dissanayake <jsdjayanga@gmail.com>
=> Adding carboncontext-osgi-services.properties file

core/org.wso2.carbon.core/src/main/java/org/wso2/carbon/core/internal/CarbonCoreServiceComponent.java, core/org.wso2.carbon.utils/src/main/java/org/wso2/carbon/context/CarbonCoreInitializedEvent.java, core/org.wso2.carbon.utils/src/main/java/org/wso2/carbon/context/CarbonCoreInitializedEventImpl.java, core/org.wso2.carbon.utils/src/main/java/org/wso2/carbon/context/internal/CarbonContextServiceComponent.java
Signed-off-by: Jayanga Dissanayake <jsdjayanga@gmail.com>
=> Commiting fix for the CARBON-15213, patch provided by Thusitha

core/org.wso2.carbon.ndatasource.rdbms/src/main/java/org/wso2/carbon/ndatasource/rdbms/utils/RDBMSDataSourceUtils.java
JIRA : https://wso2.org/jira/browse/CARBON-15239
=> Fixes For CARBON-15239

core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/AbstractUserStoreManager.java, core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/util/UserCoreUtil.java
Reverts wso2/carbon4-kernel#185
=> Merging fix for IDENTITY-3130 again

core/org.wso2.carbon.core/src/main/java/org/wso2/carbon/core/multitenancy/utils/TenantAxisUtils.java
Reverts wso2/carbon4-kernel#205
=> Revert "Fix ESBJAVA-3683"

core/org.wso2.carbon.registry.core/src/main/java/org/wso2/carbon/registry/core/config/RegistryConfigurationProcessor.java, core/org.wso2.carbon.registry.core/src/main/java/org/wso2/carbon/registry/core/config/RegistryContext.java, core/org.wso2.carbon.registry.core/src/main/java/org/wso2/carbon/registry/core/utils/RegistryUtils.java, distribution/kernel/carbon-home/repository/conf/registry.xml
Reverts wso2/carbon4-kernel#211
=> Revert "adding changes to make resource cache timeout configurable"

core/org.wso2.carbon.core/src/main/java/org/wso2/carbon/core/multitenancy/utils/TenantAxisUtils.java
Reverts wso2/carbon4-kernel#228
=> Merging Fix on ESBJAVA-3683

core/org.wso2.carbon.core/src/main/java/org/wso2/carbon/core/multitenancy/MultitenantMessageReceiver.java
fix for JIRA issue https://wso2.org/jira/browse/DS-879
=> Copy tenenantOut message context's some fields to mainOut message context

core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/ldap/ReadWriteLDAPUserStoreManager.java
Added check for more elements, and changed returnedUserEntry to empty string from null string
=> Fix for IDENTITY-3348

core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/authorization/JDBCAuthorizationManager.java
Fix for [1]
[1] https://wso2.org/jira/browse/CARBON-15265
=> Fix for CARBON-15265

core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/ldap/ReadOnlyLDAPUserStoreManager.java
Reverts wso2/carbon4-kernel#255
=> Revert "Fix for IDENTITY-3264"

core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/jdbc/JDBCUserStoreConstants.java
Reused variables from the JDBCRealmConstants
=> fixed consistency issue

core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/ldap/ReadOnlyLDAPUserStoreManager.java
To avoid multiple LDAP bindings for failed user name
=> Rearrange LDAP Authent. Logic 

core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/ldap/ReadOnlyLDAPUserStoreManager.java
Exception trowing logic changed
=> Identity 3387 : changed the Exception trowing logic

core/org.wso2.carbon.core/src/main/java/org/wso2/carbon/core/multitenancy/MultitenantMessageReceiver.java, core/org.wso2.carbon.core/src/main/java/org/wso2/carbon/core/multitenancy/MultitenantRESTServlet.java, core/org.wso2.carbon.ui/src/main/java/org/wso2/carbon/ui/CarbonUILoginUtil.java, core/org.wso2.carbon.ui/src/main/java/org/wso2/carbon/ui/util/CharacterEncoder.java, core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/AbstractUserStoreManager.java, core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/jdbc/JDBCUserStoreManager.java, core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/ldap/ActiveDirectoryUserStoreConstants.java, core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/ldap/ReadOnlyLDAPUserStoreConstants.java, core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/ldap/ReadOnlyLDAPUserStoreManager.java, core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/ldap/ReadWriteLDAPUserStoreConstants.java, core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/ldap/ReadWriteLDAPUserStoreManager.java, core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/tenant/CommonHybridLDAPTenantManager.java, core/org.wso2.carbon.utils/src/main/java/org/wso2/carbon/context/CarbonContext.java, distribution/integration/tests-integration/tests/src/test/java/org/wso2/carbon/integration/tests/carbontools/CarbonServerBasicOperationTestCase.java, distribution/integration/tests-integration/tests/src/test/java/org/wso2/carbon/integration/tests/carbontools/CarbonServerCommandPortOffsetTestCase.java, distribution/integration/tests-integration/tests/src/test/java/org/wso2/carbon/integration/tests/carbontools/DsetupCommandTestCase.java, distribution/integration/tests-integration/tests/src/test/java/org/wso2/carbon/integration/tests/carbontools/RunBuildXMLTestCase.java, distribution/integration/tests-integration/tests/src/test/java/org/wso2/carbon/integration/tests/integration/ServerRestartTestCase.java, distribution/integration/tests-integration/tests/src/test/java/org/wso2/carbon/integration/tests/integration/ServerShutdownTestCase.java, distribution/integration/tests-integration/tests/src/test/java/org/wso2/carbon/integration/tests/jira/issues/test/CARBON15203GSONBuilderOrderTestCase.java, distribution/integration/tests-integration/tests/src/test/resources/instrumentation.txt, distribution/integration/tests-integration/tests/src/test/resources/testng-server-mgt.xml, parent/pom.xml
Following commits are cherry-pick from the master branch
https://github.com/wso2/carbon4-kernel/commit/4abb310 
https://github.com/wso2/carbon4-kernel/commit/6ffe323 
https://github.com/wso2/carbon4-kernel/commit/1e9db69
https://github.com/wso2/carbon4-kernel/commit/ce68b85
https://github.com/wso2/carbon4-kernel/commit/f3c9271
https://github.com/wso2/carbon4-kernel/commit/3213146
https://github.com/wso2/carbon4-kernel/commit/6f75e7e
https://github.com/wso2/carbon4-kernel/commit/b284ce3
https://github.com/wso2/carbon4-kernel/commit/b376661
https://github.com/wso2/carbon4-kernel/commit/9b7b94f
https://github.com/wso2/carbon4-kernel/commit/2f8c009
=> Merge commits to the release branch which are done on Master branch

core/org.wso2.carbon.tomcat/src/main/java/org/wso2/carbon/tomcat/jndi/CarbonJavaURLContextFactory.java
Reverts wso2/carbon4-kernel#265
=> Revert "Webapp lookup context read only issue fixed" : CARBON-15274

core/org.wso2.carbon.core/pom.xml, core/org.wso2.carbon.core/src/main/java/org/wso2/carbon/core/clustering/hazelcast/HazelcastClusteringAgent.java, core/org.wso2.carbon.core/src/main/java/org/wso2/carbon/core/clustering/hazelcast/HazelcastDistributedMapProvider.java, core/org.wso2.carbon.core/src/main/java/org/wso2/carbon/core/clustering/hazelcast/HazelcastGroupManagementAgent.java, core/org.wso2.carbon.core/src/main/java/org/wso2/carbon/core/clustering/hazelcast/wka/WKABasedMembershipScheme.java, features/org.wso2.carbon.core.common.feature/pom.xml, parent/pom.xml
Depends on https://github.com/wso2/orbit/pull/95
=> CARBON-15247 - Upgrade Hazelcast version to 3.4.2

distribution/kernel/carbon-home/repository/conf/security/authenticators.xml
added the ACSURL to authenticators.xml
=> FIX for IDENTITY-2872

core/org.wso2.carbon.core/src/main/java/org/wso2/carbon/core/clustering/hazelcast/HazelcastClusteringAgent.java
Currently in Carbon the membership schemes are not extendible. As a result Carbon Core component needs to be patched if a new membership scheme needs to be added. In this pull request I have implemented an extension model for plugging in custom membership schemes for Hazelcast clustering.
Implement a custom Membership Scheme and package it in a JAR/OSGi bundle. Copy it to the Carbon server repository/components/lib or repository/components/dropins folder. Then update the axis2.xml file with the required values. 
Example:
[Private PaaS Membership Scheme] (https://github.com/wso2/product-private-paas/tree/master/extensions/carbon/ppaas-membership-scheme)
```
<clustering class="org.wso2.carbon.core.clustering.hazelcast.HazelcastClusteringAgent"
enable="true">
<parameter …
```
=> Carbon Clustering Membership Scheme Extension Model for Carbon 4.4.x

core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/AbstractUserStoreManager.java
Catching non existent users and throwing exceptions in claim handling.
=> Fixing IDENTITY-3469

distribution/kernel/carbon-home/repository/conf/carbon.xml, distribution/kernel/carbon-home/repository/conf/security/xss-patterns.properties
…e will be added at product build time
=> Improvements to XSS fix

core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/jdbc/JDBCUserStoreManager.java, core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/system/SystemUserRoleManager.java
Insufficient Entropy fix request for 4.4.x.
=> Fixing insufficient entropy issue in veracode report.

core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/jdbc/JDBCUserStoreManager.java, core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/system/SystemUserRoleManager.java, core/org.wso2.carbon.utils/src/main/java/org/wso2/carbon/utils/CarbonEntityResolver.java, core/org.wso2.carbon.utils/src/main/java/org/wso2/carbon/utils/CarbonUtils.java
Insufficient entropy fix request to master branch.
=> Fix insufficient entropy

core/org.wso2.carbon.utils/src/main/java/org/wso2/carbon/utils/CarbonEntityResolver.java, core/org.wso2.carbon.utils/src/main/java/org/wso2/carbon/utils/CarbonUtils.java
XXE issue fix request to master branch.
=> Add fixing XXE issues in veracode report.

core/org.wso2.carbon.utils/src/main/java/org/wso2/carbon/utils/CarbonEntityResolver.java, core/org.wso2.carbon.utils/src/main/java/org/wso2/carbon/utils/CarbonUtils.java
XXE issue fix request to 4.4.x
=> Fix XXE issues of veracode report.

core/org.wso2.carbon.ui/src/main/java/org/wso2/carbon/ui/filters/CSRFConstants.java, core/org.wso2.carbon.ui/src/main/java/org/wso2/carbon/ui/filters/CSRFException.java, core/org.wso2.carbon.ui/src/main/java/org/wso2/carbon/ui/filters/CSRFFilterConfig.java, core/org.wso2.carbon.ui/src/main/java/org/wso2/carbon/ui/filters/CSRFPreventionFilter.java, core/org.wso2.carbon.ui/src/main/java/org/wso2/carbon/ui/filters/CSRFProtector.java, core/org.wso2.carbon.ui/src/main/java/org/wso2/carbon/ui/filters/CSRFResponseWrapper.java, core/org.wso2.carbon.ui/src/main/java/org/wso2/carbon/ui/filters/ResponseWrapperOutputStream.java, core/org.wso2.carbon.ui/src/main/resources/web/admin/js/csrf.js
This PR adds a filter to prevent CSRF Injection
=> Fixing CSRF Injection

core/org.wso2.carbon.tomcat/src/main/java/org/wso2/carbon/tomcat/internal/CarbonTomcat.java
Please check JIRA before merging PR.
=> CARBON-15388 : Unable to log into Carbon Console when appbase path contains some repeating folder name in Virtual Host

core/org.wso2.carbon.core/src/main/java/org/wso2/carbon/core/multitenancy/MultitenantServerManager.java, core/org.wso2.carbon.core/src/main/java/org/wso2/carbon/core/multitenancy/eager/TenantEagerLoader.java, core/org.wso2.carbon.core/src/main/java/org/wso2/carbon/core/multitenancy/eager/TenantLoadingConfig.java, core/org.wso2.carbon.core/src/main/java/org/wso2/carbon/core/multitenancy/utils/TenantAxisUtils.java, distribution/kernel/carbon-home/repository/conf/carbon.xml
Need to discuss on adding this since the Eager Loading configuration is changed.
=> CARBON-15215 - Eager loaded tenants get unloaded after tenant.idle.time

core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/ldap/ReadOnlyLDAPUserStoreManager.java
Removing from list ldap internal server users from lists when claim is surname
=> fix for IDENTITY-3485
